[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "riva"
version = "0.1.0"
description = "Riva Personal AI Assistant"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[tool.setuptools.packages.find]
where = ["src", "."]
include = ["riva*", "app*"]